mod categories;
mod delivery_staff;
mod discounts;
mod orders;
mod prices;
mod products;
mod reconciliation_statement;
mod roles;
mod tenants;
mod users;
mod workspace;

pub(crate) use categories::categories_routes;
pub(crate) use delivery_staff::delivery_staff_routes;
pub(crate) use discounts::discount_routes;
pub(crate) use orders::order_routes;
pub(crate) use prices::prices_routes;
pub(crate) use products::products_routes;
pub(crate) use reconciliation_statement::reconciliation_statement_routes;
pub(crate) use roles::roles_routes;
pub(crate) use tenants::tenant_routes;
pub(crate) use users::user_routes;
pub(crate) use workspace::workspace_routes;
